# Generated by Django 3.0.8 on 2020-07-13 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='usuario',
        ),
    ]
